import type { Politician } from "./types";

/**
 * DEMO DATA — illustrative roster for Fantasy Hill prototyping.
 * Excludes President, Vice President, and Supreme Court.
 * Names and scores are for demo UX only, not live scoring.
 */
export const DEMO_BANNER =
  "DEMO DATA — sample politicians & scores for product preview. Not live legislative scoring.";

export const POLITICIANS: Politician[] = [
  // Senators
  {
    id: "sen-warren",
    name: "Elizabeth Warren",
    party: "D",
    state: "MA",
    category: "senator",
    title: "U.S. Senator",
    demoPoints: 42,
    lastAction: "Cosponsored banking oversight bill",
  },
  {
    id: "sen-cruz",
    name: "Ted Cruz",
    party: "R",
    state: "TX",
    category: "senator",
    title: "U.S. Senator",
    demoPoints: 38,
    lastAction: "Floor amendment on energy permitting",
  },
  {
    id: "sen-murphy",
    name: "Chris Murphy",
    party: "D",
    state: "CT",
    category: "senator",
    title: "U.S. Senator",
    demoPoints: 35,
    lastAction: "Advanced gun-safety markup",
  },
  {
    id: "sen-cotton",
    name: "Tom Cotton",
    party: "R",
    state: "AR",
    category: "senator",
    title: "U.S. Senator",
    demoPoints: 33,
    lastAction: "Defense authorization amendment",
  },
  {
    id: "sen-klobuchar",
    name: "Amy Klobuchar",
    party: "D",
    state: "MN",
    category: "senator",
    title: "U.S. Senator",
    demoPoints: 31,
    lastAction: "Antitrust hearing leadership",
  },
  {
    id: "sen-rubio",
    name: "Marco Rubio",
    party: "R",
    state: "FL",
    category: "senator",
    title: "U.S. Senator",
    demoPoints: 29,
    lastAction: "Foreign relations report filed",
  },
  {
    id: "sen-booker",
    name: "Cory Booker",
    party: "D",
    state: "NJ",
    category: "senator",
    title: "U.S. Senator",
    demoPoints: 28,
    lastAction: "Justice reauthorization cosponsor",
  },
  {
    id: "sen-blackburn",
    name: "Marsha Blackburn",
    party: "R",
    state: "TN",
    category: "senator",
    title: "U.S. Senator",
    demoPoints: 27,
    lastAction: "Tech oversight letter & hearing",
  },
  // Representatives
  {
    id: "rep-ocasio",
    name: "Alexandria Ocasio-Cortez",
    party: "D",
    state: "NY",
    category: "representative",
    title: "U.S. Representative",
    demoPoints: 44,
    lastAction: "Committee questioning + bill intro",
  },
  {
    id: "rep-gaetz",
    name: "Matt Gaetz",
    party: "R",
    state: "FL",
    category: "representative",
    title: "U.S. Representative",
    demoPoints: 36,
    lastAction: "Floor procedural votes led",
  },
  {
    id: "rep-jeffries",
    name: "Hakeem Jeffries",
    party: "D",
    state: "NY",
    category: "representative",
    title: "U.S. Representative",
    demoPoints: 40,
    lastAction: "Caucus whip count on spending",
  },
  {
    id: "rep-scalerise",
    name: "Steve Scalise",
    party: "R",
    state: "LA",
    category: "representative",
    title: "U.S. Representative",
    demoPoints: 39,
    lastAction: "Energy package floor manage",
  },
  {
    id: "rep-porter",
    name: "Katie Porter",
    party: "D",
    state: "CA",
    category: "representative",
    title: "U.S. Representative",
    demoPoints: 37,
    lastAction: "Oversight whiteboard hearing",
  },
  {
    id: "rep-jordan",
    name: "Jim Jordan",
    party: "R",
    state: "OH",
    category: "representative",
    title: "U.S. Representative",
    demoPoints: 41,
    lastAction: "Judiciary subpoena votes",
  },
  {
    id: "rep-pressley",
    name: "Ayanna Pressley",
    party: "D",
    state: "MA",
    category: "representative",
    title: "U.S. Representative",
    demoPoints: 30,
    lastAction: "Housing markup amendments",
  },
  {
    id: "rep-mccarthy",
    name: "Kevin McCarthy",
    party: "R",
    state: "CA",
    category: "representative",
    title: "U.S. Representative",
    demoPoints: 26,
    lastAction: "Conference procedural deal",
  },
  {
    id: "rep-jayapal",
    name: "Pramila Jayapal",
    party: "D",
    state: "WA",
    category: "representative",
    title: "U.S. Representative",
    demoPoints: 34,
    lastAction: "Progressive caucus vote whip",
  },
  {
    id: "rep-massie",
    name: "Thomas Massie",
    party: "R",
    state: "KY",
    category: "representative",
    title: "U.S. Representative",
    demoPoints: 32,
    lastAction: "Discharge petition cosign",
  },
  // Senate leadership
  {
    id: "lead-schumer",
    name: "Chuck Schumer",
    party: "D",
    state: "NY",
    category: "senate_leadership",
    title: "Senate Majority Leader",
    demoPoints: 55,
    lastAction: "Scheduled cloture on nominations",
  },
  {
    id: "lead-thune",
    name: "John Thune",
    party: "R",
    state: "SD",
    category: "senate_leadership",
    title: "Senate Minority Whip",
    demoPoints: 48,
    lastAction: "Opposition whip on spending",
  },
  {
    id: "lead-durbin",
    name: "Dick Durbin",
    party: "D",
    state: "IL",
    category: "senate_leadership",
    title: "Senate Majority Whip",
    demoPoints: 46,
    lastAction: "Judiciary calendar advance",
  },
  {
    id: "lead-barrasso",
    name: "John Barrasso",
    party: "R",
    state: "WY",
    category: "senate_leadership",
    title: "Senate Conference Chair",
    demoPoints: 43,
    lastAction: "Conference messaging vote",
  },
  // House leadership
  {
    id: "lead-johnson",
    name: "Mike Johnson",
    party: "R",
    state: "LA",
    category: "house_leadership",
    title: "Speaker of the House",
    demoPoints: 58,
    lastAction: "Rules Committee calendar set",
  },
  {
    id: "lead-jeffries-lead",
    name: "Hakeem Jeffries (Leadership)",
    party: "D",
    state: "NY",
    category: "house_leadership",
    title: "House Minority Leader",
    demoPoints: 52,
    lastAction: "Minority strategy on CR",
  },
  {
    id: "lead-emmer",
    name: "Tom Emmer",
    party: "R",
    state: "MN",
    category: "house_leadership",
    title: "House Majority Whip",
    demoPoints: 47,
    lastAction: "Whip count on farm bill",
  },
  {
    id: "lead-clark",
    name: "Katherine Clark",
    party: "D",
    state: "MA",
    category: "house_leadership",
    title: "House Minority Whip",
    demoPoints: 45,
    lastAction: "Democratic whip operation",
  },
  // Federal leadership (generic bucket for Format B)
  {
    id: "fed-murray",
    name: "Patty Murray",
    party: "D",
    state: "WA",
    category: "federal_leadership",
    title: "Senate President Pro Tempore",
    demoPoints: 44,
    lastAction: "Appropriations package steer",
  },
  {
    id: "fed-comerty",
    name: "James Comer",
    party: "R",
    state: "KY",
    category: "federal_leadership",
    title: "House Oversight Chair",
    demoPoints: 49,
    lastAction: "Oversight hearing + letters",
  },
  // Governors
  {
    id: "gov-newsom",
    name: "Gavin Newsom",
    party: "D",
    state: "CA",
    category: "governor",
    title: "Governor",
    demoPoints: 50,
    lastAction: "Signed climate package",
  },
  {
    id: "gov-abbott",
    name: "Greg Abbott",
    party: "R",
    state: "TX",
    category: "governor",
    title: "Governor",
    demoPoints: 48,
    lastAction: "Executive order on border ops",
  },
  {
    id: "gov-whitmer",
    name: "Gretchen Whitmer",
    party: "D",
    state: "MI",
    category: "governor",
    title: "Governor",
    demoPoints: 41,
    lastAction: "Infrastructure bill signing",
  },
  {
    id: "gov-desantis",
    name: "Ron DeSantis",
    party: "R",
    state: "FL",
    category: "governor",
    title: "Governor",
    demoPoints: 46,
    lastAction: "Education rulemaking package",
  },
  {
    id: "gov-hochul",
    name: "Kathy Hochul",
    party: "D",
    state: "NY",
    category: "governor",
    title: "Governor",
    demoPoints: 36,
    lastAction: "Budget deal with legislature",
  },
  {
    id: "gov-youngkin",
    name: "Glenn Youngkin",
    party: "R",
    state: "VA",
    category: "governor",
    title: "Governor",
    demoPoints: 34,
    lastAction: "Veto + amendment cycle",
  },
  // State upper
  {
    id: "su-ca-atkins",
    name: "Toni Atkins",
    party: "D",
    state: "CA",
    category: "state_upper",
    title: "State Senate President",
    demoPoints: 28,
    lastAction: "State senate bill package",
  },
  {
    id: "su-tx-patrick",
    name: "Dan Patrick",
    party: "R",
    state: "TX",
    category: "state_upper",
    title: "Lieutenant Governor / Senate",
    demoPoints: 31,
    lastAction: "Priority bills through senate",
  },
  {
    id: "su-ny-stewart",
    name: "Andrea Stewart-Cousins",
    party: "D",
    state: "NY",
    category: "state_upper",
    title: "State Senate Majority Leader",
    demoPoints: 27,
    lastAction: "Housing reform vote",
  },
  {
    id: "su-fl-passidomo",
    name: "Kathleen Passidomo",
    party: "R",
    state: "FL",
    category: "state_upper",
    title: "State Senate President",
    demoPoints: 25,
    lastAction: "Insurance reform passage",
  },
  // State lower
  {
    id: "sl-ca-rivas",
    name: "Robert Rivas",
    party: "D",
    state: "CA",
    category: "state_lower",
    title: "State Assembly Speaker",
    demoPoints: 29,
    lastAction: "Assembly floor package",
  },
  {
    id: "sl-tx-burrows",
    name: "Dustin Burrows",
    party: "R",
    state: "TX",
    category: "state_lower",
    title: "State House Speaker",
    demoPoints: 30,
    lastAction: "House calendar control",
  },
  {
    id: "sl-ny-heaton",
    name: "Carl Heastie",
    party: "D",
    state: "NY",
    category: "state_lower",
    title: "State Assembly Speaker",
    demoPoints: 26,
    lastAction: "Budget conference deal",
  },
  {
    id: "sl-fl-renner",
    name: "Paul Renner",
    party: "R",
    state: "FL",
    category: "state_lower",
    title: "State House Speaker",
    demoPoints: 24,
    lastAction: "Property tax measure",
  },
  // State legislator (generic for Format B)
  {
    id: "stleg-pa-costa",
    name: "Jay Costa",
    party: "D",
    state: "PA",
    category: "state_legislator",
    title: "State Senator",
    demoPoints: 22,
    lastAction: "Committee bill report",
  },
  {
    id: "stleg-oh-huffman",
    name: "Matt Huffman",
    party: "R",
    state: "OH",
    category: "state_legislator",
    title: "State Senate President",
    demoPoints: 23,
    lastAction: "Redistricting process vote",
  },
  // Cabinet / Agency (exclude POTUS/VP/SCOTUS)
  {
    id: "cab-blinken",
    name: "Antony Blinken",
    party: "D",
    state: "DC",
    category: "cabinet_agency",
    title: "Secretary of State",
    demoPoints: 40,
    lastAction: "Treaty negotiation brief",
  },
  {
    id: "cab-yellen",
    name: "Janet Yellen",
    party: "D",
    state: "DC",
    category: "cabinet_agency",
    title: "Secretary of the Treasury",
    demoPoints: 38,
    lastAction: "Sanctions package issued",
  },
  {
    id: "cab-buttigieg",
    name: "Pete Buttigieg",
    party: "D",
    state: "DC",
    category: "cabinet_agency",
    title: "Secretary of Transportation",
    demoPoints: 33,
    lastAction: "Infrastructure grant awards",
  },
  {
    id: "cab-garland",
    name: "Merrick Garland",
    party: "D",
    state: "DC",
    category: "cabinet_agency",
    title: "Attorney General",
    demoPoints: 35,
    lastAction: "DOJ enforcement action",
  },
  {
    id: "cab-granholm",
    name: "Jennifer Granholm",
    party: "D",
    state: "DC",
    category: "cabinet_agency",
    title: "Secretary of Energy",
    demoPoints: 32,
    lastAction: "Clean energy loan program",
  },
  {
    id: "cab-mayorkas",
    name: "Alejandro Mayorkas",
    party: "D",
    state: "DC",
    category: "cabinet_agency",
    title: "Secretary of Homeland Security",
    demoPoints: 37,
    lastAction: "Border policy directive",
  },
];

export function getPolitician(id: string): Politician | undefined {
  return POLITICIANS.find((p) => p.id === id);
}

export function politiciansByCategory(
  categories: Politician["category"][],
): Politician[] {
  return POLITICIANS.filter((p) => categories.includes(p.category));
}

export const CATEGORY_LABELS: Record<Politician["category"], string> = {
  senator: "Senator",
  representative: "Representative",
  senate_leadership: "Senate Leadership",
  house_leadership: "House Leadership",
  federal_leadership: "Federal Leadership",
  governor: "Governor",
  state_upper: "State Upper",
  state_lower: "State Lower",
  state_legislator: "State Legislator",
  cabinet_agency: "Cabinet / Agency",
};
